# .prettierrc.toml

useTabs = false
tabWidth = 2
printWidth = 80
endOfLine = "lf"

# -- Not supported yet --
# trailingComma = "es5"
# embeddedLanguageFormatting = "auto"

# Example override
# overrides = [
#   { files = ["tests/*.rs"], options = { printWidth = 80 } }
# ]